### PR TITLE
Proper Mac Commands handling

### LINKED ISSUE #1120: Mac Commands piggybacked on the Fopts should not be ignored
image
Currently we only process mac commands in case they are in the main payload. We also need to process the mac commands piggybacked in the Fopts

### LINKED ISSUE #1174: `ConcentratorDeduplicationDataMessagesIntegrationTests` relies on broken requests for tests
## Expected Behavior

`ConcentratorDeduplicationDataMessagesIntegrationTests` tests should not rely on faulty requests and failing data processing to test deduplication.

## Current Behavior

Some tests in `ConcentratorDeduplicationDataMessagesIntegrationTests` throw when decrypting the payload of a request that is used for these deduplication tests. This happens because the `AppSKey` is not set at all (and also: the network session keys used in these tests are invalid).

When trying to mitigate the failed payload decryption by using correct keys in e.g. `When_Mac_Command_Should_Not_Send_Upstream_Messages_And_Should_Skip_Calls_To_FrameCounterDown_When_SoftDuplicate`:

```csharp
this.loraABPDevice.Deduplication = DeduplicationMode.None; // or Mark
this.loraABPDevice.NwkSKey = "ABCD2000000000000000000000000009";
this.loraABPDevice.AppSKey = "ABCD2000000000000000000000000009";
```

this causes the payload decryption not to fail any longer. At the same time, the test assertions start to fail. We should make sure that these tests do not rely on broken payload decryption to work properly.

### LINKED ISSUE #1203: When FPort == 0, payload should be decrypted with the nwkskey
Currently, DefaultLoRaDataRequestHandler is decrypting the payload always with AppSKey, but that's an issue since we should decrypt it with the NwkSKey when FPort == 0

### PR DESCRIPTION
**Pull request by danigian**
# Mac Commands handling

## What is being addressed

This PR is tackling following issues:

- [x] Fixes #1203
- [x] Fixes #1120
- [x] Fixes #1174
 
## How is this addressed

- [x] Logic in DefaultLoRaDataRequestHandler has been modified 
- [x] When_Mac_Command_Should_Not_Send_Upstream_Messages_And_Should_Skip_Calls_To_FrameCounterDown_When_SoftDuplicate integration test has been re-enabled for properly working
- [x] Persists_Reported_Dwell_Time_On_TxParamSetupAns DwellTimeIntegrationTest has been modified to test both FOpts and Payload sending of the Mac Command Answer

### CODE REVIEW

File: LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/DefaultLoRaDataRequestHandler.cs [hunk 1]
```diff
@@ -223,51 +225,48 @@ public async Task<LoRaDeviceRequestProcessResult> ProcessRequestAsync(LoRaReques
...
-                                {
-                                    this.logger.LogDebug("Received 'TxParamSetupAns' even though reported dwell time settings match desired dwell time settings.");
-                                }
+                                loRaDevice.UpdateDwellTimeSetting(someRegion.DesiredDwellTimeSetting, acceptChanges: false);
+                                _ = await loRaDevice.SaveChangesAsync(force: true);
                             }
                             else
                             {
-                                this.logger.LogWarning("Received 'TxParamSetupAns' in region '{Region}' which does not support dwell limitations.", request.Region.LoRaRegion);
+                                this.logger.LogDebug("Received 'TxParamSetupAns' even though reported dwell time settings match desired dwell time settings.");
```
Comment (Mandur) [inline LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/DefaultLoRaDataRequestHandler.cs:259]: Why debug and not warning here?

Comment (Mandur) [reply LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/DefaultLoRaDataRequestHandler.cs:259]: sorry understood

File: Tests/Common/SimulatedDevice.cs [hunk 2]
```diff
@@ -126,7 +126,14 @@ public LoRaPayloadData CreateUnconfirmedDataUpMessage(string data, uint? fcnt =
                 direction,
                 Supports32BitFCnt ? fcnt : null);
 
-            payloadData.Serialize(appSKey is { } someAppSessionKey ? someAppSessionKey : AppSKey ?? throw new InvalidOperationException($"Can't perform encryption without {nameof(AppSKey)}."));
+            if (fport == FramePort.MacCommand)
+            {
+                payloadData.Serialize(nwkSKey is { } someNwkSessionKey ? someNwkSessionKey : NwkSKey ?? throw new InvalidOperationException($"Can't perform encryption without {nameof(AppSKey)}."));
```
Comment (Mandur) [inline Tests/Common/SimulatedDevice.cs:131]:
```suggestion
                payloadData.Serialize(nwkSKey is { } someNwkSessionKey ? someNwkSessionKey : NwkSKey ?? throw new InvalidOperationException($"Can't perform encryption without {nameof(NwkSKey)} when fport is set to 0."));
```

File: Tests/Common/SimulatedDevice.cs [hunk 3]
```diff
@@ -170,9 +177,26 @@ public LoRaPayloadData CreateConfirmedDataUpMessage(string data, uint? fcnt = nu
...
+                                                  fcntBytes,
+                                                  null,
+                                                  fport,
+                                                  payload,
+                                                  direction,
+                                                  Supports32BitFCnt ? fcnt : null);
+
+            if (fport == FramePort.MacCommand)
+            {
+                payloadData.Serialize(nwkSKey is { } someNwkSessionKey ? someNwkSessionKey : NwkSKey ?? throw new InvalidOperationException($"Can't perform encryption without {nameof(AppSKey)}."));
```
Comment (Mandur) [inline Tests/Common/SimulatedDevice.cs:192]:
```suggestion
                payloadData.Serialize(nwkSKey is { } someNwkSessionKey ? someNwkSessionKey : NwkSKey ?? throw new InvalidOperationException($"Can't perform encryption without {nameof(NwkSKey)} when fport is set to 0."));
```

**Review by Mandur — APPROVED** [review]
