### PR TITLE
Fix wrongly Datarate mapping for class C devices

### LINKED ISSUE #192: Sending direct message to Class C device
I'm in the process of testing sending direct messages to class C devices - specifically UrsaLink UC1152 devices.  My device is set up for US915 frequencies.  I worked through an issue with the edgeHub which resulted in the following error message while invoking a direct message to the LoRaWanNetworkSrvModule

```
[DirectMethod] Invoking Direct Method [ClearCache] to [xxxxxx/LoRaWanNetworkSrvModule] ...
[DirectMethod] Failed to invoke Direct Method: Not found
```
To resolve the aforementioned error, I shutdown my device and invoked 
```
sudo iotedge restart edgeHub
sudo iotedge restart LoRaWanNetworkSrvModule
```
then restarted my device to rejoin the network - thanks to @Mandur and @fbeltrao for helping me resolve that issue.  After that I was able to successfully send a direct message to the LoRaWanNetworkSrvModule as seen in my logs[1] however the message does not appear to be reaching my device as I am not seeing any downlink messages being recorded in the devices management utility[2].

I have tried to send messages with "payload" and "rawPayload" with the latter being base64 encoded.  Both message result in the same behavior.

At this point I am at a loss on how to debug why my direct messages are not reaching the class C device.  Any help would be much appreciated.

[1] LoRaWanNetworkSrvModule logs
```
2019-06-13 16:19:26.733 Log Level: Debug
2019-06-13 16:19:26.753 LoRaWAN server started on port 1680
2019-06-13 16:19:51.497 Statistic: {"stat":{"time":"2019-06-13 16:19:51 GMT","rxnb":0,"rxok":0,"rxfw":0,"ackr":0.0,"dwnb":0,"txnb":0}}
2019-06-13 16:20:21.469 Statistic: {"stat":{"time":"2019-06-13 16:20:21 GMT","rxnb":0,"rxok":0,"rxfw":0,"ackr":100.0,"dwnb":0,"txnb":0}}
2019-06-13 16:20:51.473 Statistic: {"stat":{"time":"2019-06-13 16:20:51 GMT","rxnb":0,"rxok":0,"rxfw":0,"ackr":100.0,"dwnb":0,"txnb":0}}
2019-06-13 16:21:21.469 Statistic: {"stat":{"time":"2019-06-13 16:21:21 GMT","rxnb":0,"rxok":0,"rxfw":0,"ackr":100.0,"dwnb":0,"txnb":0}}
2019-06-13 16:21:47.851 Physical dataUp {"rxpk":[{"tmst":733168242,"chan":8,"rfch":0,"freq":903.000000,"stat":1,"modu":"LORA","datr":"SF8BW500","codr":"4/5","lsnr":8.2,"rssi":-48,"size":23,"data":"AExrbmlMQHJVIjATkiJhUhHQPfWvc7M="}]}
2019-06-13 16:21:48.105 1152612292133022: join request received
2019-06-13 16:21:48.118 1152612292133022: querying the registry for OTAA device
2019-06-13 16:21:48.889 1152612292133022: using edgeHub local queue
2019-06-13 16:21:49.072 1152612292133022: getting device twin
2019-06-13 16:21:50.102 1152612292133022: done getting device twin
2019-06-13 16:21:50.560 1152612292133022: updating twin
2019-06-13 16:21:50.996 1152612292133022: twin updated
2019-06-13 16:21:51.051 1152612292133022: device added to cache
2019-06-13 16:21:51.322 UDP: sending message with ID 6DC9, to 172.18.0.1:57992
2019-06-13 16:21:51.325 UDP: message sent with ID 6DC9
2019-06-13 16:21:51.327 UDP: packet with id 6DC9 successfully transmitted by the aggregator
2019-06-13 16:21:51.330 1152612292133022: processing time: 00:00:03.4792686
2019-06-13 16:21:51.330 1152612292133022: JoinAccept {"txpk":{"imme":false,"data":"IKo385Fl2h2z22Fe2rbjJUU=","tmst":738168242,"size":17,"freq":923.3,"rfch":0,"modu":"LORA","datr":"SF7BW500","codr":"4/5","powe":14,"ipol":true}}
2019-06-13 16:21:51.473 Statistic: {"stat":{"time":"2019-06-13 16:21:51 GMT","rxnb":1,"rxok":1,"rxfw":1,"ackr":100.0,"dwnb":1,"txnb":0}}
2019-06-13 16:21:57.281 Physical dataUp {"rxpk":[{"tmst":742597868,"chan":1,"rfch":0,"freq":902.500000,"stat":1,"modu":"LORA","datr":"SF10BW125","codr":"4/5","lsnr":9.0,"rssi":-47,"size":23,"data":"AExrbmlMQHJVIjATkiJhUhHLpggUmj0="}]}
2019-06-13 16:21:57.282 1152612292133022: join request received
2019-06-13 16:21:57.283 1152612292133022: querying the registry for OTAA device
2019-06-13 16:21:57.425 1152612292133022: updating twin
2019-06-13 16:21:57.436 1152612292133022: twin updated
2019-06-13 16:21:57.443 1152612292133022: device added to cache
2019-06-13 16:21:57.443 1152612292133022: previous device devAddr (03A79CF8) removed from cache.
2019-06-13 16:21:57.443 UDP: sending message with ID 550B, to 172.18.0.1:57992
2019-06-13 16:21:57.444 UDP: message sent with ID 550B
2019-06-13 16:21:57.444 1152612292133022: processing time: 00:00:00.1643870
2019-06-13 16:21:57.444 1152612292133022: JoinAccept {"txpk":{"imme":false,"data":"IBdvBR2dWP4qsq1tKU0zeqA=","tmst":747597868,"size":17,"freq":923.9,"rfch":0,"modu":"LORA","datr":"SF10BW500","codr":"4/5","powe":14,"ipol":true}}
2019-06-13 16:21:57.445 UDP: packet with id 550B successfully transmitted by the aggregator
2019-06-13 16:22:09.399 1152612292133022: received cloud to device message from direct method: {"devEUI":"1152612292133022","fport":"1","messageId":"0001","confirmed":true,"payload":"HeaterOn"}
2019-06-13 16:22:09.438 1152612292133022: [class-c] down frame counter: 1
2019-06-13 16:22:09.453 1152612292133022: using standard second receive window
2019-06-13 16:22:09.645 1152612292133022: ConfirmedDataDown {"txpk":{"imme":true,"data":"oFRmYAMAAQABRH8lpTaUh5JKSS4o","tmst":0,"size":21,"freq":923.3,"rfch":0,"modu":"LORA","datr":"SF12BW500","codr":"4/5","powe":14,"ipol":true}}
2019-06-13 16:22:09.645 UDP: sending message with ID 4370, to 172.18.0.1:57992
2019-06-13 16:22:09.645 UDP: message sent with ID 4370
2019-06-13 16:22:09.647 UDP: packet with id 4370 successfully transmitted by the aggregator
2019-06-13 16:22:21.470 Statistic: {"stat":{"time":"2019-06-13 16:22:21 GMT","rxnb":1,"rxok":1,"rxfw":1,"ackr":100.0,"dwnb":2,"txnb":3}}
2019-06-13 16:22:51.477 Statistic: {"stat":{"time":"2019-06-13 16:22:51 GMT","rxnb":0,"rxok":0,"rxfw":0,"ackr":100.0,"dwnb":0,"txnb":0}}

```

[2] UrsaLink device utility
image

image

image

image

image

### PR DESCRIPTION
**Pull request by Mandur**
Fix #192 

* Add RX2 computation to class C
* Added differentiation between valid upstream and downstream DR

### CODE REVIEW

File: LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaDevice.cs [hunk 1]
```diff
@@ -833,7 +833,7 @@ internal async Task<bool> UpdateAfterJoinAsync(LoRaDeviceJoinUpdateProperties up
                     reportedProperties[TwinProperty.RX1DROffset] = null;
                 }
 
-                if (this.DesiredRX2DataRate != DefaultJoinValues && currentRegion.RegionLimits.IsCurrentDRIndexWithinAcceptableValue(this.DesiredRX2DataRate))
+                if (this.DesiredRX2DataRate != DefaultJoinValues && currentRegion.DRtoConfiguration.ContainsKey(this.DesiredRX2DataRate))
```
Comment (debugerr) [inline LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaDevice.cs]: couldn't we keep that validation in the RegionLimits method? I liked the encapsulation we had before without having to tangle with the dictionary here directly. If it is not really fitting the RegionLimits anymore, we may be able to add a method to the Region directly encapsulating that lookup?

Comment (debugerr) [reply LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaDevice.cs]: Looks like you already did that: IsCurrentDRIndexWithinAcceptableValue. Can we use that instead here and the other places where the direct lookups take place?

File: LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Regions/Region.cs [hunk 2]
```diff
@@ -156,6 +156,18 @@ public bool TryGetDownstreamChannelFrequency(Rxpk upstreamChannel, out double fr
             return false;
         }
 
+        public bool IsCurrentDRIndexWithinAcceptableValue(uint dr)
```
Comment (debugerr) [inline LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Regions/Region.cs]: could simplify to: 

return this.DRtoConfiguration.ContainsKey(dr)

File: LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Regions/Region.cs [hunk 3]
```diff
@@ -240,11 +252,11 @@ public uint GetMaxPayloadSize(string datr)
         /// <summary>
         /// This method Check that a received packet is within the correct frenquency range and has a valid Datr.
         /// </summary>
-        private bool IsValidRxpk(Rxpk rxpk)
+        private bool IsValidUpstreamRxpk(Rxpk rxpk)
         {
             if (rxpk.Freq < this.RegionLimits.FrequencyRange.min ||
                 rxpk.Freq > this.RegionLimits.FrequencyRange.max ||
-                !this.RegionLimits.DatarateRange.Contains(rxpk.Datr))
+                !this.RegionLimits.UpstreamValidDR.Contains(rxpk.Datr))
```
Comment (debugerr) [inline LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Regions/Region.cs]: nit: maybe also add wrappers for these instead of direct dictionary access.

File: LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Regions/RegionLimits.cs [hunk 4]
```diff
@@ -13,24 +13,15 @@ public class RegionLimits
...
-            if (dr < this.DatarateRange.Count)
-            {
-                return true;
-            }
-            else
-            {
-                return false;
-            }
-        }
+        public HashSet<string> UpstreamValidDR { get; set; }
```
Comment (debugerr) [inline LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Regions/RegionLimits.cs]: If you end up adding methods to lookup in here, make these private. Having them exposed as public is opening up direct manipulation to it. Keeping them private helps with protecting your state.

File: LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Regions/RegionManager.cs [hunk 5]
```diff
@@ -128,7 +130,7 @@ private static void CreateEU868Region()
             { 6, 5, 4, 3, 2, 1 },
             { 7, 6, 5, 4, 3, 2 }
             };
-            List<string> euValidDataranges = new List<string>()
+            HashSet<string> validDatarange = new HashSet<string>()
```
Comment (debugerr) [inline LoRaEngine/modules/LoRaWanNetworkSrvModule/LoraTools/Regions/RegionManager.cs]: nit: rename to validDataRangeUpAndDownstream

File: LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaDevice.cs (hunk 1 above)
Comment (Mandur) [reply LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaDevice.cs]: The problem is that the input there is the DR index (uint) and my dictionary is a string. I fixed this in my previous implementation by looking at the dictionary size, which was sadly one of the problem causing this bug. I could implement it within the limit class, but then I would need to know the current region... Which defeat the idea of having a limit class imho. But happy to discuss on a call if you have other ideas.

Comment (Mandur) [reply LoRaEngine/modules/LoRaWanNetworkSrvModule/LoRaWan.NetworkServer/LoRaDevice.cs]: Wait I have an idea
